<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <InvariantGlobalization>true</InvariantGlobalization>
        <ApplicationIcon>data/logo.ico</ApplicationIcon>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\FNA\FNA.Core.csproj"/>
        <PackageReference Include="Exec-Ultralight.FNA" Version="0.1.2"/>
        <PackageReference Include="ValvePak" Version="4.0.0.142"/>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Debug'">
        <None Include="data\resources\*">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup Condition="'$(Configuration)' == 'Release'">
        <None Condition="Exists('data\ui.vpk')" Include="data\ui.vpk">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
        <None Condition="Exists('data\shaders.vpk')" Include="data\shaders.vpk">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>

    <ItemGroup>
        <None Include="lib\*.dll">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
            <Link>%(Filename)%(Extension)</Link>
        </None>
    </ItemGroup>

</Project>
